version: '4.0'

services:
  db:
    container_name: "supre_db"
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "admin548"
      PGADMIN_LISTEN_PORT: 80
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - "8800:80/tcp"
    restart: unless-stopped



  web:
    build: .
    command: sh -c "make back"
    container_name: larixon
    restart: always
    volumes:
      - .:/code/
    ports:
      - "8000:8000"
    env_file:
      - .env-dev


volumes:
  db-data:
  pgadmin-data: