# Generated by Django 4.2.5 on 2023-09-25 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"default_related_name": "Category"},
        ),
        migrations.AlterModelOptions(
            name="city",
            options={"default_related_name": "City"},
        ),
    ]
